version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-app --capabilities CAPABILITY_IAM --region us-east-1 --resolve-s3
artifacts:
  files:
    - template.yaml
